### PR TITLE
Pot Extractor

### PR DESCRIPTION
**Pull request by joaoantunes87**
Pot extractor following Nico suggestions.
Once there are no .po files, this loader had not been integrated yet.

### CODE REVIEW

**Comment by jason-p-pickering** [comment]
@joaoantunes87 what is the status of this PR? I  was going to ask @varl  to review it.

**Comment by joaoantunes87** [comment]
Hi @jason-p-pickering ,
Right now, the i18n files in json are missing (./i18n/{{lng}}.json). 

Or, as I think we prefer, instead we add .po files and do the same as in Translations App: a script to fetch .po files and generate those .json files. This will need some development.

**Comment by jason-p-pickering** [comment]
OK. No rush on this. @varl what do you think. Should we schedule this for 2.30?

**Comment by varl** [comment]
@joaoantunes87 The `pot-extractor.js`; is this a way to migrate from the d2-i18n to i18next? If this tool is generic, could we use it for other apps too?

@jason-p-pickering Yeah, 2.30 sounds good to me; there's activity related to the limbo between d2-i18n and i18next which I would like to clear up first. Some (new) apps are implementing both in the interim, some apps are getting new strings in i18next but keeps the old in d2-i18n and I haven't taken the time to get involved in the technical details of migrating yet.

**Comment by joaoantunes87** [comment]
Hi @varl,
The pot-extractor.js is not a generic tool. The idea is to create a pot file with i18n keys found in the source code. However, each application has it own structure and way of using keys, so it needs to be updated. The pot-extractor.js is a step among others in the translation flow. POT file will be used by translators to generate need .po files.

We have written a document for what we have on done on translations-app. It would be good if you had the time to give a check on it:
https://docs.google.com/document/d/1I7t9dE46HUj4d7cieuub7eN6qa4DembN7wcYM_tNNGI/edit?usp=sharing

**Comment by HendrikThePendric** [comment]
Closing this because by now we have `@dhis2/d2-i18n`, making this PR redundant

**Pull request closed without merging**
