### PR TITLE
Disabled the empty lists

### PR DESCRIPTION
**Pull request by adhbh**
Fix for https://github.com/dhis2/settings-app/issues/39

### CODE REVIEW

**Comment by nicolayr** [comment]
@adhbh Thanks for the pull request.

However the issue here is that the drop down lists are empty - either because the options haven't loaded yet or because there are no options to display in the database. Your pull request simply disables the input field when there are no options to display, which doesn't really address the issue. Disabling the field might be a good idea, but there also needs to be a placeholder value there.

**Comment by adhbh** [comment]
Is it fine if I disable the select if there is no options with the placeholder? Should the placeholder value for each Select field be same?

**Comment by nicolayr** [comment]
To be honest I'm not sure if the control should be disabled or not when there are no options. It depends on how this is implemented in Material-UI, and I haven't looked into it. But I'd say it's probably a good idea to disable the control.

For the placeholder value, it would be good to add a new prop such as `emptyLabel`. If no `emptyLabel` prop is specified, a default, and translated, label should be used. For example `no_options_available`.

**Comment by nicolayr** [comment]
I'm going to close this pull request since it doesn't solve the issue - but feel free to make a new one @adhbh

**Pull request closed without merging**
