### PR TITLE
feat: port to app-platform

### PR DESCRIPTION
**Pull request by mediremi**
Closes https://jira.dhis2.org/browse/DHIS2-9387

# Feature files
[Here](https://github.com/dhis2/settings-app/tree/c40072c5c06e2cfa64f7ef821114527aaa574b09/cypress/integration)

# Changes

# Required as part of port

- :warning: Removed existing translations localed under `i18n/modules` as they were in the wrong format. [Transifex config has been updated so that they are (hopefully) restored once this is merged](https://github.com/dhis2/settings-app/pull/800/files#diff-e071df9d84c80d98b07a7efe464ea1b4e92ab493b5c52f5d0f37ca69266ebc3fL3-L10)
- :warning: [Use `@dhis2/d2-i18n` instead of `d2.18n.getTranslation.`](https://github.com/dhis2/settings-app/blob/d15626531c409246a6c6bc6172d8b34413d7a2e8/src/settingsKeyMapping.js) As the keys used by `d2.18n.getTranslation` were `snake_case` instead of English sentences, this may require some Transifex configuration. 
- [Subscribe `localizedAppearanceEditor` to `settingsStore`](https://github.com/dhis2/settings-app/blob/d15626531c409246a6c6bc6172d8b34413d7a2e8/src/localized-text/LocalizedAppearanceEditor.component.js#L96-L104)
- [Use data query for initialising options store](https://github.com/dhis2/settings-app/blob/d15626531c409246a6c6bc6172d8b34413d7a2e8/src/App.js)

# Functional changes

- Use `Modal` from `@dhis2/ui` instead of material UI for previewing uploaded
  images and OAuth2 clients
- Use `Table` from `@dhis2/ui` for OAuth2 clients

### CODE REVIEW

**Review by Mohammer5 — CHANGES_REQUESTED** [review]
> ## Feature files
> Here

:tada: :tada: :tada: :tada:

There are small issues with the feature files, we have a document that states what they should look like: https://github.com/dhis2/notes/blob/master/howto/writing_feature_files.md
(It's quite hidden...)

**Comment by Mohammer5** [comment]
I'm getting the following error when starting the app (I've already removed the `node_modules` & `.d2` folders, cleaned yarn's cache):

image

**Comment by mediremi** [comment]
> I'm getting the following error when starting the app (I've already removed the node_modules & .d2 folders, cleaned yarn's cache):

There's no `src/serviceWorker.js` so I have no idea how that's possible :confused: Can I see the full stack trace?

**Comment by Mohammer5** [comment]
There is no stacktrace because it happens in the index.js right away, but there's more:

image

**Review by Mohammer5 — APPROVED** [review]
Looks ok to me!
Can't say much about the translation stuff that you mentioned.
App starts, seems to work as expected.

**Pull request merged**
