### PR TITLE
fix: update settings names [DHIS2-7630]

### PR DESCRIPTION
**Pull request by tomzemp**
@scottrusspatrick: this updates the settings names [as you requested in Jira](https://jira.dhis2.org/browse/DHIS2-7630?focusedCommentId=39901&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-39901)

### CODE REVIEW

**Review by benguaraldi — APPROVED** [review]
Looks good to me!

**Comment by Philip-Larsen-Donnelly** [comment]
@benguaraldi 
I'm not really happy with you merging to core apps; even though the change is trivial, and you are a trusted partner of the core team.
I would prefer for you to shout or scream at me or the platform team leads (@amcgee , @varl ) if things are time-critical.

**Comment by benguaraldi** [comment]
@Philip-Larsen-Donnelly Sorry about that—I thought I had enough information from @scottrusspatrick that he wanted this, but I can understand if that doesn't work.

**Comment by Philip-Larsen-Donnelly** [comment]
@benguaraldi 
It's not that we don't want the change; it's more the principle that the core dev team should have an overview, and control, of what goes in to the code base.

**Pull request merged**
